#version 430 core

layout(local_size_x = 64, local_size_y = 2, local_size_z = 2) in;

layout(std430, binding = 0) buffer FloatBuffer {
    float vertices[];
};

layout(std430, binding = 1) buffer u {
    restrict int U[];
};

layout(std430, binding = 2) buffer v {
    restrict int V[];
};

layout(std430, binding = 3) buffer w {
    restrict int W[];
};

layout(std430, binding = 11) buffer outcount {
    int count;
};

uniform int maxWidth;
uniform int maxHeight;

void main() {
    int y = int(gl_GlobalInvocationID.y);
    int z = int(gl_GlobalInvocationID.z);
    int x = int(gl_GlobalInvocationID.x);

    int yxw = y * maxWidth;
    int zxwxh = z * maxWidth * maxHeight;
    int current = x + yxw + zxwxh;

    int dXpos = (x + 1) + yxw + zxwxh;
    int dYpos = x + ((y + 1) * maxWidth) + zxwxh;
    int dZpos = x + yxw + ((z + 1) * maxWidth * maxHeight);

    /*
    bool d =
    ((abs(U[dXpos]) > 0) ||
    (abs(U[current]) > 0) ||
    (abs(V[dYpos]) > 0) ||
    (abs(V[current]) > 0) ||
    (abs(W[dZpos]) > 0) ||
    (abs(W[current] > 0)));*/

    int vIndex = x + (y * maxWidth) + (z * maxWidth * (maxHeight + 1));

    if (abs(V[vIndex]) <= 0) return;

    int now = atomicAdd(count, 1);

    vertices[now * 3] = x;
    vertices[now * 3 + 1] = y;
    vertices[now * 3 + 2] = z;
}
