#version 430 core

layout(local_size_x = 2, local_size_y = 2, local_size_z = 2) in;

layout(std430, binding = 2) buffer v {
    int V[];
};

layout(std430, binding = 9) buffer vw {
    restrict int VW[];
};

uniform int maxWidth;

uniform int dY;

void main() {
    int x = int(gl_GlobalInvocationID.x);
    int y = int(gl_GlobalInvocationID.y);
    int z = int(gl_GlobalInvocationID.z);

    V[x + (y * maxWidth) + (z * maxWidth * dY)] = 0;
    VW[x + (y * maxWidth) + (z * maxWidth * dY)] = 0;
}
